DELIMITER //
CREATE PROCEDURE buyoilproc (IN AMOUNT INT, IN CID INT, IN TRID INT, IN COMMTYPE INT , OUT RET INT)
    BEGIN
    DECLARE CUR_PRICE INT;
    DECLARE CUR_CLIENT_LEVEL INT;
    DECLARE CUR_OIL DECIMAL(65,4);
    DECLARE CUR_CASH DECIMAL(65,4);
    DECLARE CUR_RATE DECIMAL(65,4);
    DECLARE COMM_CASH DECIMAL(65,4);
    DECLARE COMM_OIL DECIMAL(65,4);
    DECLARE BASE_CASH DECIMAL(65,4);
    DECLARE AFT_CASH DECIMAL(65,4);
    DECLARE AFT_OIL DECIMAL(65,4);
    DECLARE TID INT;

    SELECT PRICE FROM OILPRICES ORDER BY PRICE_DATE DESC LIMIT 1 INTO CUR_PRICE;
    SELECT LEVEL, OIL_BALAN, CASH_BALAN FROM CLIENTS WHERE UID = CID INTO CUR_CLIENT_LEVEL, CUR_OIL, CUR_CASH;

    IF CUR_CLIENT_LEVEL = 0 THEN
        SELECT RATE_SILVER FROM COMM_RATES ORDER BY RATE_DATE DESC LIMIT 1 INTO CUR_RATE;
    ELSE
        SELECT RATE_GOLD FROM COMM_RATES ORDER BY RATE_DATE DESC LIMIT 1 INTO CUR_RATE;
    END IF;
    IF COMMTYPE = 0 THEN
        SET COMM_OIL = AMOUNT * CUR_RATE;
        SET COMM_CASH = 0.0;
    ELSE
        SET COMM_OIL = 0.0;
        SET COMM_CASH = AMOUNT * CUR_PRICE * CUR_RATE;
    END IF;
    SET BASE_CASH = AMOUNT * CUR_PRICE;
    SET AFT_CASH = CUR_CASH - COMM_CASH - BASE_CASH;
    SET AFT_OIL = CUR_OIL - COMM_OIL + AMOUNT;
    UPDATE CLIENTS SET OIL_BALAN = AFT_OIL, CASH_BALAN = AFT_CASH;
    INSERT INTO CLIENTS_TRANS (T_DATE, C_ID, TR_ID) VALUES (NOW(), CID, TRID);
    SELECT LAST_INSERT_ID() INTO TID;
    INSERT INTO OIL_TRANSACTIONS (T_ID, COMM_OIL, COMM_CASH, OIL_BALAN, CASH_BALAN, COMM_RATE, PRICE, AMOUNT) VALUES (TID, COMM_OIL, COMM_CASH, AFT_OIL, AFT_CASH, CUR_RATE, CUR_PRICE, AMOUNT);
    SET RET = TID;
END//
