USE BRYNHILDR;
CREATE EVENT rating_monthly_event ON SCHEDULE EVERY 1 MONTH STARTS DATE_ADD(DATE_ADD(DATE_SUB(CURDATE(),INTERVAL DAY(CURDATE())-1 DAY),INTERVAL 1 MONTH), INTERVAL 0 HOUR) ON COMPLETION PRESERVE ENABLE DO CALL rating_monthly();
