USE BRYNHILDR;
DELIMITER //
CREATE TRIGGER cancel_payment_trigger
    AFTER DELETE
    ON PAYMENTS FOR EACH ROW
    BEGIN
DELETE FROM CLIENTS_TRANS WHERE T_ID = OLD.T_ID;
    END;//

CREATE TRIGGER cancel_oil_trigger
    AFTER DELETE
    ON OIL_TRANSACTIONS FOR EACH ROW
    BEGIN
DELETE FROM CLIENTS_TRANS WHERE T_ID = OLD.T_ID;
    END;//
DELIMITER ;
