USE BRYNHILDR;
DROP TRIGGER IF EXISTS cancel_payment_trigger;
DROP TRIGGER IF EXISTS cancel_oil_trigger;
DELIMITER //
CREATE TRIGGER cancel_payment_trigger
    AFTER DELETE
    ON PAYMENTS FOR EACH ROW
    BEGIN
    SELECT T_DATE, C_ID, TR_ID, T_TYPE FROM CLIENTS_TRANS WHERE T_ID = OLD.T_ID INTO @T_DATE, @C_ID, @TR_ID, @T_TYPE;
    INSERT INTO CANCEL_LOGS (C_DATE, T_DATE, T_ID, C_ID, TR_ID, T_TYPE, CASH_BALAN, AMOUNT) VALUES (NOW(), @T_DATE, OLD.T_ID, @C_ID, @TR_ID, @T_TYPE, OLD.CASH_BALAN, OLD.AMOUNT);
    DELETE FROM CLIENTS_TRANS WHERE T_ID = OLD.T_ID;
    END//

CREATE TRIGGER cancel_oil_trigger
    AFTER DELETE
    ON OIL_TRANSACTIONS FOR EACH ROW
    BEGIN
    INSERT INTO CANCEL_LOGS (C_DATE, T_DATE, T_ID, C_ID, TR_ID, T_TYPE, COMM_OIL, COMM_CASH, OIL_BALAN, CASH_BALAN, COMM_RATE, PRICE, AMOUNT) VALUES (NOW(), @T_DATE, OLD.T_ID, @C_ID, @TR_ID, @T_TYPE, OLD.COMM_OIL, OLD.COMM_CASH, OLD.OIL_BALAN, OLD.CASH_BALAN, OLD.COMM_RATE, OLD.PRICE, OLD.AMOUNT);
    DELETE FROM CLIENTS_TRANS WHERE T_ID = OLD.T_ID;
    END//
DELIMITER ;
